all:
	g++ caffe_test.cpp -I/home/tsornson/programming/caffe/caffe/include/ -I/home/tsornson/programming/caffe/caffe/src/caf -L/home/tsornson/programming/caffe/caffe/build/lib -DCPU_ONLY -lglog -lcaffe -lprotobuf
